package common.system;

import java.lang.String;

/**
 * Generated by JavaPoet.
 * @see <a href="https://github.com/square/javapoet">https://github.com/square/javapoet</a>
 */
public class IntegrityValues {
  public static final String BOOTSTRAP_SCRIPT = "smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T";

  public static final String BOOTSTRAP_STYLE = "WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB";

  public static final String BOOTSTRAP_STYLE_JAPAN = "y9cpQTq+kHdGqrZNRqEv0FfWtq3qGBH89pCXmUjWrWh9XMNDkCGd9ktOn2gV/Sot";

  public static final String BOOTSTRAP_STYLE_PRETTY = "GX5+zFzUk7QendD2UmTGbuAV7hnPc80+e++2lPDH8fi499/qslNobFHRD6swXNHw";

  public static final String JQUERY_SCRIPT = "tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT";

  public static final String JQUERY_UI_SCRIPT = "PtTRqvDhycIBU6x1wwIqnbDo8adeWIWP3AHmnrvccafo35E7oIvW7HPXn2YimvWu";

  public static final String JQUERY_UI_STYLE = "VK/ia2DWrvtO05YDcbWI8WE3WciOH0RhfPNuRJGSa3dpAs5szXWQuCnPNv/yzpO4";

  private IntegrityValues() {
  }
}
