package common.system;

import java.lang.String;

/**
 * Generated by JavaPoet.
 * @see <a href="https://github.com/square/javapoet">https://github.com/square/javapoet</a>
 */
public class IntegrityValues {
  public static final String BOOTSTRAP_SCRIPT = "uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm";

  public static final String BOOTSTRAP_STYLE = "9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4";

  public static final String BOOTSTRAP_STYLE_JAPAN = "O2O43qjOqR+haT7lKX6qlK0VqDOgQUplOHKOjHHeBdYzORnQmYPRFtf8pyLDqAa2";

  public static final String BOOTSTRAP_STYLE_PRETTY = "LADyp1h75+9o79SPQh05XqELMjwVHbHEvwBbMpZIgTgX2kf17Xm7B9uVoB19cGm5";

  public static final String JQUERY_SCRIPT = "tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT";

  public static final String JQUERY_UI_SCRIPT = "PtTRqvDhycIBU6x1wwIqnbDo8adeWIWP3AHmnrvccafo35E7oIvW7HPXn2YimvWu";

  public static final String JQUERY_UI_STYLE = "VK/ia2DWrvtO05YDcbWI8WE3WciOH0RhfPNuRJGSa3dpAs5szXWQuCnPNv/yzpO4";

  private IntegrityValues() {
  }
}
