package common.system;

import java.lang.String;

/**
 * Generated by JavaPoet.
 * @see <a href="https://github.com/square/javapoet">https://github.com/square/javapoet</a>
 */
public class MessageKeys {
  public static final String ABANDONED = "abandoned";

  public static final String ABOUT__X = "about_x";

  public static final String ACCESS = "access";

  public static final String ADD = "add";

  public static final String ADOBE_READER_LINK = "adobe.reader.link";

  public static final String AFTER = "after";

  public static final String ALERT = "alert";

  public static final String ALIGNMENT = "alignment";

  public static final String ALL = "all";

  public static final String AMBIGUOUS = "ambiguous";

  public static final String ANALYSES = "analyses";

  public static final String ANSWER = "answer";

  public static final String APPEARANCE = "appearance";

  public static final String APPEARANCE_AUTO = "appearance.auto";

  public static final String APPEARANCE_DARK = "appearance.dark";

  public static final String APPEARANCE_LIGHT = "appearance.light";

  public static final String APPLICATION = "application";

  public static final String ARRANGE = "arrange";

  public static final String ARROW = "arrow";

  public static final String AUDIO = "audio";

  public static final String AUTHENTICATION = "authentication";

  public static final String AUTHORIZATION = "authorization";

  public static final String AUTO = "auto";

  public static final String BACK = "back";

  public static final String BADGE = "badge";

  public static final String BATCH = "batch";

  public static final String BEFORE = "before";

  public static final String BOOTBOX_LANG = "bootbox.lang";

  public static final String BOOTSTRAP = "bootstrap";

  public static final String BOTTOM = "bottom";

  public static final String BROWSE = "browse";

  public static final String BROWSER = "browser";

  public static final String BULK = "bulk";

  public static final String BUTTON = "button";

  public static final String CAMERA = "camera";

  public static final String CAMPAIGN = "campaign";

  public static final String CANCEL = "cancel";

  public static final String CAPTURE = "capture";

  public static final String CARD = "card";

  public static final String CENTER = "center";

  public static final String CHANGE = "change";

  public static final String CHANGEUSER = "changeuser";

  public static final String CHANGEUSER_DECISION_COMPLETE = "changeuser.decision.complete";

  public static final String CHANGEUSER_DECISION_COMPLETE_DESCRIPTION = "changeuser.decision.complete.description";

  public static final String CHANGEUSER_DECISION_MAIL_SUBJECT = "changeuser.decision.mail.subject";

  public static final String CHANGEUSER_PLEASE__CHANGE = "changeuser.please_change";

  public static final String CHANGEUSER_PLEASE__CHANGE_DESCRIPTION = "changeuser.please_change.description";

  public static final String CHANGEUSER_RESERVE_COMPLETE = "changeuser.reserve.complete";

  public static final String CHANGEUSER_RESERVE_COMPLETE_DESCRIPTION = "changeuser.reserve.complete.description";

  public static final String CHANGEUSER_RESERVE_MAIL_SUBJECT = "changeuser.reserve.mail.subject";

  public static final String CHARACTER = "character";

  public static final String CHAT = "chat";

  public static final String CHECKBOX = "checkbox";

  public static final String CLEAR = "clear";

  public static final String CLIENT = "client";

  public static final String CLOCK = "clock";

  public static final String CLOSE = "close";

  public static final String CODEPOINT = "codepoint";

  public static final String COLOR = "color";

  public static final String COLUMN = "column";

  public static final String COMPANY = "company";

  public static final String COMPANY_NAME = "company.name";

  public static final String COMPANY_NAME_DESCRIPTION = "company.name.description";

  public static final String COMPLETE = "complete";

  public static final String COMPLETED = "completed";

  public static final String COMPONENT = "component";

  public static final String CONDITION = "condition";

  public static final String CONSISTENT = "consistent";

  public static final String CONSTRAINT_EMAIL = "constraint.email";

  public static final String CONSTRAINT_MAX = "constraint.max";

  public static final String CONSTRAINT_MAXLENGTH = "constraint.maxLength";

  public static final String CONSTRAINT_MIN = "constraint.min";

  public static final String CONSTRAINT_MINLENGTH = "constraint.minLength";

  public static final String CONSTRAINT_PATTERN = "constraint.pattern";

  public static final String CONSTRAINT_REQUIRED = "constraint.required";

  public static final String CONSULT = "consult";

  public static final String CONTACT = "contact";

  public static final String CONTENT = "content";

  public static final String CONVERT = "convert";

  public static final String COOPERATE = "cooperate";

  public static final String COPY = "copy";

  public static final String COUNTRY_FLAG = "country.flag";

  public static final String CREATE = "create";

  public static final String CREATOR = "creator";

  public static final String CURRENCY = "currency";

  public static final String CUT = "cut";

  public static final String DANGER = "danger";

  public static final String DATATABLES_LANG = "datatables.lang";

  public static final String DATE = "date";

  public static final String DATETIME = "datetime";

  public static final String DAY = "day";

  public static final String DAYLIGHT__SAVING__TIME = "daylight_saving_time";

  public static final String DECIMAL = "decimal";

  public static final String DEFAULT = "default";

  public static final String DELETE = "delete";

  public static final String DESCRIPTION = "description";

  public static final String DESELECT = "deselect";

  public static final String DESIGN = "design";

  public static final String DETAIL = "detail";

  public static final String DEVELOPMENT = "development";

  public static final String DIRECTION = "direction";

  public static final String DISPLAY = "display";

  public static final String DOCUMENT = "document";

  public static final String DOWN = "down";

  public static final String DOWNLOAD = "download";

  public static final String DRAG = "drag";

  public static final String DRAWER = "drawer";

  public static final String DROP = "drop";

  public static final String ECHARTS_LANG = "echarts.lang";

  public static final String EDIT = "edit";

  public static final String EMAIL = "email";

  public static final String EMPTY = "empty";

  public static final String END = "end";

  public static final String ENTER = "enter";

  public static final String ENVIRONMENT = "environment";

  public static final String ERROR = "error";

  public static final String ERROR_DATE = "error.date";

  public static final String ERROR_EMAIL = "error.email";

  public static final String ERROR_EXPECTED_DATE = "error.expected.date";

  public static final String ERROR_EXPECTED_DATE_ISOFORMAT = "error.expected.date.isoformat";

  public static final String ERROR_EXPECTED_ENUMSTRING = "error.expected.enumstring";

  public static final String ERROR_EXPECTED_JSARRAY = "error.expected.jsarray";

  public static final String ERROR_EXPECTED_JSBOOLEAN = "error.expected.jsboolean";

  public static final String ERROR_EXPECTED_JSNUMBER = "error.expected.jsnumber";

  public static final String ERROR_EXPECTED_JSNUMBERORJSSTRING = "error.expected.jsnumberorjsstring";

  public static final String ERROR_EXPECTED_JSOBJECT = "error.expected.jsobject";

  public static final String ERROR_EXPECTED_JSSTRING = "error.expected.jsstring";

  public static final String ERROR_EXPECTED_KEYPATHNODE = "error.expected.keypathnode";

  public static final String ERROR_EXPECTED_TIME = "error.expected.time";

  public static final String ERROR_EXPECTED_UUID = "error.expected.uuid";

  public static final String ERROR_EXPECTED_VALIDENUMVALUE = "error.expected.validenumvalue";

  public static final String ERROR_INVALID = "error.invalid";

  public static final String ERROR_INVALID_JAVA_UTIL_DATE = "error.invalid.java.util.Date";

  public static final String ERROR_MAX = "error.max";

  public static final String ERROR_MAXLENGTH = "error.maxLength";

  public static final String ERROR_MAX_STRICT = "error.max.strict";

  public static final String ERROR_MIN = "error.min";

  public static final String ERROR_MINLENGTH = "error.minLength";

  public static final String ERROR_MIN_STRICT = "error.min.strict";

  public static final String ERROR_NUMBER = "error.number";

  public static final String ERROR_PATH_EMPTY = "error.path.empty";

  public static final String ERROR_PATH_MISSING = "error.path.missing";

  public static final String ERROR_PATH_RESULT_MULTIPLE = "error.path.result.multiple";

  public static final String ERROR_PATTERN = "error.pattern";

  public static final String ERROR_REAL = "error.real";

  public static final String ERROR_REAL_PRECISION = "error.real.precision";

  public static final String ERROR_REQUIRED = "error.required";

  public static final String ERROR_UUID = "error.uuid";

  public static final String ESSENTIAL = "essential";

  public static final String ETERNAL = "eternal";

  public static final String EXAMPLE = "example";

  public static final String FAILED = "failed";

  public static final String FAILURE = "failure";

  public static final String FAQ = "faq";

  public static final String FIELD = "field";

  public static final String FILE = "file";

  public static final String FILE_NAME = "file.name";

  public static final String FILTER = "filter";

  public static final String FIRST = "first";

  public static final String FIRST__TIME = "first_time";

  public static final String FONT = "font";

  public static final String FONTAWESOME = "fontawesome";

  public static final String FONT_HIRAGINOSANS__W3 = "font.hiraginosans_w3";

  public static final String FONT_HIRAMINPRON__W3 = "font.hiraminpron_w3";

  public static final String FONT_IPAMJMINCHO = "font.ipamjmincho";

  public static final String FOOTER = "footer";

  public static final String FORMAT = "format";

  public static final String FORMATS_DATE = "formats.date";

  public static final String FORMAT_DATE = "format.date";

  public static final String FORMAT_NUMERIC = "format.numeric";

  public static final String FORMAT_REAL = "format.real";

  public static final String FORMAT_UUID = "format.uuid";

  public static final String FORWARD = "forward";

  public static final String FRAMEWORK = "framework";

  public static final String FRAPPEGANTT_LANG = "frappegantt.lang";

  public static final String FULLCALENDAR_LANG = "fullcalendar.lang";

  public static final String FULL__NAME = "full_name";

  public static final String FULL__SCREEN = "full_screen";

  public static final String FULL__TEXT = "full_text";

  public static final String GENERAL = "general";

  public static final String GET = "get";

  public static final String GROUP = "group";

  public static final String HALF__DAY = "half_day";

  public static final String HANDSONTABLE_LANG = "handsontable.lang";

  public static final String HEADER = "header";

  public static final String HELP = "help";

  public static final String HEX = "hex";

  public static final String HIDE = "hide";

  public static final String HOME = "home";

  public static final String HORIZONTAL = "horizontal";

  public static final String HTTP = "http";

  public static final String ICON = "icon";

  public static final String ID = "id";

  public static final String IMAGE = "image";

  public static final String INFO = "info";

  public static final String INFORMATION = "information";

  public static final String INITIALIZE = "initialize";

  public static final String INPUT = "input";

  public static final String INQUIRY = "inquiry";

  public static final String INQUIRY_SEND = "inquiry.send";

  public static final String INQUIRY_SEND_COMPLETE = "inquiry.send.complete";

  public static final String INQUIRY_SEND_COMPLETE_DESCRIPTION = "inquiry.send.complete.description";

  public static final String INQUIRY_SEND_DESCRIPTION = "inquiry.send.description";

  public static final String INSERT__COLUMN__LEFT = "insert_column_left";

  public static final String INSERT__COLUMN__RIGHT = "insert_column_right";

  public static final String INSERT__ROW__ABOVE = "insert_row_above";

  public static final String INSERT__ROW__BELOW = "insert_row_below";

  public static final String INTEGER = "integer";

  public static final String INTRO = "intro";

  public static final String JAVA = "java";

  public static final String JAVASCRIPT = "javascript";

  public static final String JAVA_ERROR_ASSERTFALSE = "java.error.AssertFalse";

  public static final String JAVA_ERROR_ASSERTTRUE = "java.error.AssertTrue";

  public static final String JAVA_ERROR_DECIMALMAX = "java.error.DecimalMax";

  public static final String JAVA_ERROR_DECIMALMIN = "java.error.DecimalMin";

  public static final String JAVA_ERROR_DIGITS = "java.error.Digits";

  public static final String JAVA_ERROR_EMAIL = "java.error.Email";

  public static final String JAVA_ERROR_FUTURE = "java.error.Future";

  public static final String JAVA_ERROR_FUTUREORPRESENT = "java.error.FutureOrPresent";

  public static final String JAVA_ERROR_MAX = "java.error.Max";

  public static final String JAVA_ERROR_MIN = "java.error.Min";

  public static final String JAVA_ERROR_NEGATIVE = "java.error.Negative";

  public static final String JAVA_ERROR_NEGATIVEORZERO = "java.error.NegativeOrZero";

  public static final String JAVA_ERROR_NOTBLANK = "java.error.NotBlank";

  public static final String JAVA_ERROR_NOTEMPTY = "java.error.NotEmpty";

  public static final String JAVA_ERROR_NOTNULL = "java.error.NotNull";

  public static final String JAVA_ERROR_NULL = "java.error.Null";

  public static final String JAVA_ERROR_PAST = "java.error.Past";

  public static final String JAVA_ERROR_PASTORPRESENT = "java.error.PastOrPresent";

  public static final String JAVA_ERROR_PATTERN = "java.error.Pattern";

  public static final String JAVA_ERROR_POSITIVE = "java.error.Positive";

  public static final String JAVA_ERROR_POSITIVEORZERO = "java.error.PositiveOrZero";

  public static final String JAVA_ERROR_SIZE = "java.error.Size";

  public static final String JUSTIFY = "justify";

  public static final String KEY = "key";

  public static final String KEYBOARD = "keyboard";

  public static final String LAB = "lab";

  public static final String LANGUAGE = "language";

  public static final String LAST = "last";

  public static final String LAYOUT = "layout";

  public static final String LEFT = "left";

  public static final String LIBRARY = "library";

  public static final String LICENSE = "license";

  public static final String LIGHTWEIGHTCHARTS_LANG = "lightweightcharts.lang";

  public static final String LINK = "link";

  public static final String LIST = "list";

  public static final String LOAD = "load";

  public static final String LOCAL = "local";

  public static final String LOCAL_NAME = "local.name";

  public static final String LOCAL_NAME_DESCRIPTION = "local.name.description";

  public static final String MAIL = "mail";

  public static final String MAINTENANCE = "maintenance";

  public static final String MANAGE = "manage";

  public static final String MAP = "map";

  public static final String MAPBOX_LANG = "mapbox.lang";

  public static final String MAP_LNGLAT_LAT = "map.lnglat.lat";

  public static final String MAP_LNGLAT_LNG = "map.lnglat.lng";

  public static final String MAP_ROTATE_GAMMA = "map.rotate.gamma";

  public static final String MAP_ROTATE_LAMBDA = "map.rotate.lambda";

  public static final String MAP_ROTATE_PHI = "map.rotate.phi";

  public static final String MASTER = "master";

  public static final String MAX = "max";

  public static final String MAX__CASE = "max_case";

  public static final String MENU = "menu";

  public static final String MESSAGE = "message";

  public static final String MESSAGE_CODE = "message.code";

  public static final String MIDDLE = "middle";

  public static final String MIN = "min";

  public static final String MIN__CASE = "min_case";

  public static final String MONEY = "money";

  public static final String MONTH = "month";

  public static final String MYCOMPANY_LINK = "mycompany.link";

  public static final String MYCOMPANY_NAME = "mycompany.name";

  public static final String NAME = "name";

  public static final String NAME_DESCRIPTION = "name.description";

  public static final String NATURALEARTHDATA_LANG = "naturalearthdata.lang";

  public static final String NETWORK = "network";

  public static final String NEW = "new";

  public static final String NEXT = "next";

  public static final String NOTIFICATION = "notification";

  public static final String OK = "ok";

  public static final String OLD = "old";

  public static final String OPEN = "open";

  public static final String OPENJDK = "openjdk";

  public static final String OPERATION = "operation";

  public static final String OPTIONAL = "optional";

  public static final String ORDER = "order";

  public static final String ORGANIZATION = "organization";

  public static final String ORGANIZATIONUNIT = "organizationunit";

  public static final String ORGANIZATIONUNIT_NAME = "organizationunit.name";

  public static final String ORGANIZATIONUNIT_NAME_DESCRIPTION = "organizationunit.name.description";

  public static final String OTHER = "other";

  public static final String OUTLINE = "outline";

  public static final String OUTPUT = "output";

  public static final String OVERVIEW = "overview";

  public static final String PAGE = "page";

  public static final String PAPER = "paper";

  public static final String PARAMETER = "parameter";

  public static final String PARSLEY_LANG = "parsley.lang";

  public static final String PART = "part";

  public static final String PASTE = "paste";

  public static final String PAUSE = "pause";

  public static final String PAY = "pay";

  public static final String PDF = "pdf";

  public static final String PDFJS_LANG = "pdfjs.lang";

  public static final String PHONE = "phone";

  public static final String PHOTO = "photo";

  public static final String PICKADATE_LANG = "pickadate.lang";

  public static final String PLEASE__SELECT = "please_select";

  public static final String PLEASE__WAIT = "please_wait";

  public static final String PREVIEW = "preview";

  public static final String PREVIOUS = "previous";

  public static final String PRICE = "price";

  public static final String PRINT = "print";

  public static final String PROCESS = "process";

  public static final String PRODUCT = "product";

  public static final String PROGRESS = "progress";

  public static final String QUARTER__DAY = "quarter_day";

  public static final String QUESTION = "question";

  public static final String RADIO = "radio";

  public static final String RANGE = "range";

  public static final String READ = "read";

  public static final String READ__ONLY = "read_only";

  public static final String RECEIPT = "receipt";

  public static final String RECEIVE = "receive";

  public static final String RECOVERY = "recovery";

  public static final String REDO = "redo";

  public static final String REGIST = "regist";

  public static final String REGISTUSER = "registuser";

  public static final String REGISTUSER_PLEASE__REGIST = "registuser.please_regist";

  public static final String REGISTUSER_PLEASE__REGIST_DESCRIPTION = "registuser.please_regist.description";

  public static final String REGISTUSER_PROVISIONAL_COMPLETE = "registuser.provisional.complete";

  public static final String REGISTUSER_PROVISIONAL_COMPLETE_DESCRIPTION = "registuser.provisional.complete.description";

  public static final String REGISTUSER_PROVISIONAL_MAIL_SUBJECT = "registuser.provisional.mail.subject";

  public static final String REGISTUSER_REGULAR_COMPLETE = "registuser.regular.complete";

  public static final String REGISTUSER_REGULAR_COMPLETE_DESCRIPTION = "registuser.regular.complete.description";

  public static final String REGISTUSER_REGULAR_MAIL_SUBJECT = "registuser.regular.mail.subject";

  public static final String RELOAD = "reload";

  public static final String REMOVE = "remove";

  public static final String REMOVE__COLUMN = "remove_column";

  public static final String REMOVE__ROW = "remove_row";

  public static final String REPORT = "report";

  public static final String REQUEST = "request";

  public static final String REQUIRED = "required";

  public static final String RESET = "reset";

  public static final String RESETUSER = "resetuser";

  public static final String RESETUSER_CHANGE_COMPLETE = "resetuser.change.complete";

  public static final String RESETUSER_CHANGE_COMPLETE_DESCRIPTION = "resetuser.change.complete.description";

  public static final String RESETUSER_CHANGE_MAIL_SUBJECT = "resetuser.change.mail.subject";

  public static final String RESETUSER_FORGET__PASSWORD = "resetuser.forget_password";

  public static final String RESETUSER_PLEASE__CHANGE = "resetuser.please_change";

  public static final String RESETUSER_PLEASE__CHANGE_DESCRIPTION = "resetuser.please_change.description";

  public static final String RESETUSER_PLEASE__RESET = "resetuser.please_reset";

  public static final String RESETUSER_PLEASE__RESET_DESCRIPTION = "resetuser.please_reset.description";

  public static final String RESETUSER_REQUEST_COMPLETE = "resetuser.request.complete";

  public static final String RESETUSER_REQUEST_COMPLETE_DESCRIPTION = "resetuser.request.complete.description";

  public static final String RESETUSER_REQUEST_MAIL_SUBJECT = "resetuser.request.mail.subject";

  public static final String RESPONSE = "response";

  public static final String RESTART = "restart";

  public static final String RESULT = "result";

  public static final String RIGHT = "right";

  public static final String ROW = "row";

  public static final String SAMPLE = "sample";

  public static final String SAVE = "save";

  public static final String SCAN = "scan";

  public static final String SCIENCE = "science";

  public static final String SEARCH = "search";

  public static final String SECTION = "section";

  public static final String SECURE = "secure";

  public static final String SELECT = "select";

  public static final String SELECT2_LANG = "select2.lang";

  public static final String SELECT__FILE = "select_file";

  public static final String SEND = "send";

  public static final String SERVER = "server";

  public static final String SET = "set";

  public static final String SETTING = "setting";

  public static final String SHARE = "share";

  public static final String SHEET = "sheet";

  public static final String SHOW = "show";

  public static final String SIGNATURE = "signature";

  public static final String SLIDE = "slide";

  public static final String SMS = "sms";

  public static final String SORT = "sort";

  public static final String SPEECH_SYNTHESIS_LANG = "speech.synthesis.lang";

  public static final String START = "start";

  public static final String STARTED = "started";

  public static final String STARTING = "starting";

  public static final String STATUS = "status";

  public static final String STOP = "stop";

  public static final String STOPPED = "stopped";

  public static final String STOPPING = "stopping";

  public static final String STRICT = "strict";

  public static final String STYLE = "style";

  public static final String SUBTOTAL = "subtotal";

  public static final String SUCCESS = "success";

  public static final String SUMMARY = "summary";

  public static final String SUMMERNOTE_LANG = "summernote.lang";

  public static final String SUPPORT = "support";

  public static final String SWITCH = "switch";

  public static final String SYSTEM = "system";

  public static final String SYSTEM_CONSTRAINT_HIRAGANA = "system.constraint.hiragana";

  public static final String SYSTEM_CONSTRAINT_KATAKANA = "system.constraint.katakana";

  public static final String SYSTEM_CONSTRAINT_PASSWORD = "system.constraint.password";

  public static final String SYSTEM_CONSTRAINT_USERID = "system.constraint.userid";

  public static final String SYSTEM_DESCRIPTION = "system.description";

  public static final String SYSTEM_ERROR_DATA_ILLEGAL = "system.error.data.illegal";

  public static final String SYSTEM_ERROR_DATA_UNSAVE = "system.error.data.unsave";

  public static final String SYSTEM_ERROR_EXECUTION_EXCEPTION = "system.error.execution.exception";

  public static final String SYSTEM_ERROR_EXPIRETIME_PAST = "system.error.expiretime.past";

  public static final String SYSTEM_ERROR_HIRAGANA = "system.error.hiragana";

  public static final String SYSTEM_ERROR_KATAKANA = "system.error.katakana";

  public static final String SYSTEM_ERROR_PASSWORD = "system.error.password";

  public static final String SYSTEM_ERROR_PASSWORD_NOTEQUAL = "system.error.password.notequal";

  public static final String SYSTEM_ERROR_STATE_NOTCONSISTENT = "system.error.state.notconsistent";

  public static final String SYSTEM_ERROR_STATE_UPDATEOTHERUSER = "system.error.state.updateotheruser";

  public static final String SYSTEM_ERROR_USER = "system.error.user";

  public static final String SYSTEM_ERROR_USERID = "system.error.userid";

  public static final String SYSTEM_ERROR_USERID_EXIST = "system.error.userid.exist";

  public static final String SYSTEM_ERROR_USERID_NOTEXIST = "system.error.userid.notexist";

  public static final String SYSTEM_ERROR_X_EXIST = "system.error.x.exist";

  public static final String SYSTEM_ERROR_X_ILLEGAL = "system.error.x.illegal";

  public static final String SYSTEM_ERROR_X_NOTENABLE = "system.error.x.notenable";

  public static final String SYSTEM_ERROR_X_NOTEXIST = "system.error.x.notexist";

  public static final String SYSTEM_ERROR_X__CASE__DATA_ILLEGAL = "system.error.x_case_data.illegal";

  public static final String SYSTEM_ERROR_X__DATA_ILLEGAL = "system.error.x_data.illegal";

  public static final String SYSTEM_NAME = "system.name";

  public static final String TABLE = "table";

  public static final String TALK = "talk";

  public static final String TARGET = "target";

  public static final String TASK = "task";

  public static final String TAX = "tax";

  public static final String TEMPLATE = "template";

  public static final String TEXT = "text";

  public static final String THANK__YOU = "thank_you";

  public static final String THANK__YOU__VERY__MUCH = "thank_you_very_much";

  public static final String THEME = "theme";

  public static final String THEME_BUSINESS = "theme.business";

  public static final String THEME_DEFAULT = "theme.default";

  public static final String THEME_JAPAN = "theme.japan";

  public static final String THEME_NATURAL = "theme.natural";

  public static final String THEME_PRETTY = "theme.pretty";

  public static final String TIME = "time";

  public static final String TIMELINE = "timeline";

  public static final String TIMEZONE = "timezone";

  public static final String TITLE = "title";

  public static final String TOP = "top";

  public static final String TOTAL = "total";

  public static final String TRANSLATE = "translate";

  public static final String TREE = "tree";

  public static final String TROUBLESHOOT = "troubleshoot";

  public static final String TYPE = "type";

  public static final String UI = "ui";

  public static final String UNDO = "undo";

  public static final String UP = "up";

  public static final String UPDATE = "update";

  public static final String UPLOAD = "upload";

  public static final String USER = "user";

  public static final String USER_CHANGE__USERID = "user.change_userid";

  public static final String USER_EXPIRE = "user.expire";

  public static final String USER_NEWUSERID = "user.newuserid";

  public static final String USER_NEWUSERID_DESCRIPTION = "user.newuserid.description";

  public static final String USER_PASSWORD = "user.password";

  public static final String USER_PASSWORD_DESCRIPTION = "user.password.description";

  public static final String USER_PLEASE__SIGNIN = "user.please_signin";

  public static final String USER_REPASSWORD = "user.repassword";

  public static final String USER_REPASSWORD_DESCRIPTION = "user.repassword.description";

  public static final String USER_ROLE = "user.role";

  public static final String USER_ROLE_ADMIN = "user.role.admin";

  public static final String USER_ROLE_CUSTOMER = "user.role.customer";

  public static final String USER_ROLE_GUEST = "user.role.guest";

  public static final String USER_SIGNIN = "user.signin";

  public static final String USER_SIGNOUT = "user.signout";

  public static final String USER_STORE__ACCOUNT = "user.store_account";

  public static final String USER_USERID = "user.userid";

  public static final String USER_USERID_DESCRIPTION = "user.userid.description";

  public static final String UX = "ux";

  public static final String VALUE = "value";

  public static final String VARIATION = "variation";

  public static final String VERSION = "version";

  public static final String VERTICAL = "vertical";

  public static final String VIDEO = "video";

  public static final String VIEWER = "viewer";

  public static final String WARNING = "warning";

  public static final String WEB = "web";

  public static final String WEEK = "week";

  public static final String WELCOME = "welcome";

  public static final String WIKIPEDIA_LANG = "wikipedia.lang";

  public static final String WINDOW = "window";

  public static final String WORK = "work";

  public static final String WORLD = "world";

  public static final String X__AND__X = "x_and_x";

  public static final String X__CASE__SELECTED = "x_case_selected";

  public static final String X__IS__X = "x_is_x";

  public static final String X__OF__X = "x_of_x";

  public static final String X__OR__X = "x_or_x";

  public static final String X__X = "x_x";

  public static final String YOUR__X__IS__X = "your_x_is_x";

  public static final String ZOOMIN = "zoomin";

  public static final String ZOOMOUT = "zoomout";

  private MessageKeys() {
  }
}
