INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (1, 'admin@example.com', '$2a$10$cWX4sWd6RMjm3vPfRLwTHuLcKl9ONTxHtinTyC5E8rY60gOepIVo2', 'en-US', 'UTC', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (1, 'ADMIN');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (2, 'customer@example.com', '$2a$10$ym1nzJmsAAg3aslvXUCiherutGYRHU97T6TIQ85EHycHoN.FpfR52', 'en-US', 'UTC', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (2, 'CUSTOMER');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (3, 'guest@example.com', '$2a$10$u8HwPa2ei4qB6aLDy0JjCuMbIXTAD6M.H6JgU.ZpJhLTyAob3YUBm', 'en-US', 'UTC', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (3, 'GUEST');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (4, 'adminjajp@example.com', '$2a$10$3UOujVboJa4icaNH5.tYjuwS/JHAehc6C11vvJ0zZZqFVQELXag2y', 'ja-JP', 'Asia/Tokyo', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (4, 'ADMIN');
ALTER SEQUENCE IF EXISTS HIBERNATE_SEQUENCE RESTART WITH 5;
