INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (1, 'admin@example.com', '$2a$10$qA8NVvC.wvXKo8xy5fLfAOFYg/BLFOIPOJfbdwSh7En9EOy0Ma2RK', 'en-US', 'UTC', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, 0);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (1, 'ADMIN');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (2, 'customer@example.com', '$2a$10$BmAkjkqIYQTk69nOD3X8xu9QzW3DDxIYlubWgJ/NcffQkn5385p7e', 'en-US', 'UTC', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, 0);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (2, 'CUSTOMER');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (3, 'guest@example.com', '$2a$10$TIzjR0EYSefaB.tdHFTT/OPH/j2KGjpdFZF7UhMaBanxVnhpNEA8W', 'en-US', 'UTC', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, 0);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (3, 'GUEST');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (4, 'adminjajp@example.com', '$2a$10$4oQQR7bUPaPcwgxoWsnPmuZAaZXEOOchSCHxutS.EHWiUCFx.gCm6', 'ja-JP', 'Asia/Tokyo', 'DEFAULT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, 0);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (4, 'ADMIN');
