INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, APPEARANCE, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (1, 'admin@example.com', '$2a$10$MzIUXbBuvswgvyfa05z5SOimlc8lc5q72Sel5r296510V18dM8trW', 'en-US', 'UTC', 'DEFAULT', 'LIGHT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (1, 'ADMIN');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, APPEARANCE, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (2, 'customer@example.com', '$2a$10$pKCW2GL0/QNcSRkRu69/huiJAJMaPB/Y36tenIzbTOpePbXr.0FFy', 'en-US', 'UTC', 'DEFAULT', 'LIGHT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (2, 'CUSTOMER');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, APPEARANCE, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (3, 'guest@example.com', '$2a$10$AIzTsJaXP3Zat25XsbJJK.UQ8IWkLLt98c8N1V5lyga12qsRyns2W', 'en-US', 'UTC', 'DEFAULT', 'LIGHT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (3, 'GUEST');
INSERT INTO USERS (ID, USERID, HASHEDPASSWORD, LOCALE, ZONEID, THEME, APPEARANCE, EXPIREDATETIME, SIGNINDATETIME, SIGNOUTDATETIME, UPDATEDATETIME, VERSION) VALUES (4, 'adminjajp@example.com', '$2a$10$PBSLtVdC94mQ/nZUMJ6fLeJPOnjc387EKiSM1mgbVhyb.Og.RsTfe', 'ja-JP', 'Asia/Tokyo', 'DEFAULT', 'LIGHT', '9999-12-31 23:59:59', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (4, 'ADMIN');
ALTER SEQUENCE IF EXISTS HIBERNATE_SEQUENCE RESTART WITH 5;
